// src/lib/schema.js

/**
 * @file This file defines the canonical data structures for the application,
 * matching the schemas used in smart contracts, Arweave, and The Graph.
 */

/**
 * Represents the immutable core of a conversation.
 * Stored once on Arweave.
 * @typedef {object} ConversationFile
 * @property {string} id - The unique conversation ID (e.g., "conv_1678886400000").
 * @property {string} ownerAddress - The wallet address of the owner.
 * @property {number} createdAt - The Unix timestamp (milliseconds) of creation.
 * @property {string} [branchedFromConversationId] - The ID of the conversation this was branched from.
 * @property {string} [branchedAtMessageId] - The ID of the message where the branch occurred.
 */

/**
 * Represents the mutable metadata of a conversation.
 * A new version is stored on Arweave for each update.
 * @typedef {object} ConversationMetadataFile
 * @property {string} title - The user-defined title of the conversation.
 * @property {boolean} isDeleted - A flag indicating if the conversation is deleted.
 * @property {number} lastUpdatedAt - The Unix timestamp of when the metadata (title, isDeleted) was last changed.
 * @property {number} [lastMessageCreatedAt] - The Unix timestamp of the latest message in the conversation. Used for sorting and syncing.
 * @property {string} [lastMessagePreview] - A plain text snippet of the last message for UI previews.
 */

/**
 * Represents a single message within a conversation, from either the user or the AI.
 * Stored on Arweave.
 * @typedef {object} MessageFile
 * @property {string} id - The unique message ID (e.g., "msg_1678886400001").
 * @property {string} conversationId - The ID of the parent conversation.
 * @property {string|null} parentId - The ID of the parent message, for threading.
 * @property {string|null} parentCID - The storage CID of the parent message, for history reconstruction.
 * @property {number} createdAt - The Unix timestamp (milliseconds) of creation.
 * @property {'user' | 'assistant'} role - The role of the message author.
 * @property {string | null} content - The markdown content of the message. Null if the AI is still generating.
 * @property {ReasoningStep[]} [reasoning] - An array of reasoning steps taken by the AI. Only for 'assistant' role.
 * @property {number | null} [reasoningDuration] - The duration in seconds for the AI to generate the response. Only for 'assistant' role.
 * @property {Source[]} [sources] - An array of sources cited by the AI. Only for 'assistant' role.
 */

/**
 * Represents a single step in the AI's thought process.
 * Stored as part of the MessageFile.
 * @typedef {object} ReasoningStep
 * @property {string} title - The title of the reasoning step.
 * @property {string} description - The detailed thought or action taken.
 */

/**
 * Represents a source cited by the AI.
 * @typedef {object} Source
 * @property {string} title - The title of the source document or link.
 * @property {string} url - The URL of the source.
 */

/**
 * Represents a chunk of keywords for a single message, formatted for direct
 * merging into the client-side search index.
 * @typedef {object} SearchIndexDeltaFile
 * @property {Object.<string, {cid: string, c: string}>} - A map where the key is the messageId and the value is an object containing the conversationId (cid) and keywords (c).
 * @example
 * { "msg_456": { "cid": "conv_123", "c": "bitcoin market sentiment analysis keywords" } }
 */

/**
 * Represents the final, self-contained encrypted payload that is stored on a permanent,
 * decentralized storage solution (like Arweave). This structure is generated by the TEE Oracle.
 * It is designed to be fully self-sovereign for both the user and the oracle.
 * @typedef {object} EncryptedStoragePayload
 * @property {string} encryptedContent - The core data (e.g., a MessageFile), symmetrically
 * encrypted with the Master Key. The user can decrypt this by regenerating the Master Key from their
 * wallet signature. The TEE can decrypt it by first decrypting the oracleEncryptedKey.
 * @property {string} oracleEncryptedKey - The user's original signature string, asymmetrically
 * encrypted with the TEE Oracle's public key. This serves as the TEE's permanent, independent
 * access key to the content, allowing it to regenerate the Master Key at any time.
 */
