#!/usr/bin/env sh
# Copy the canonical contract ABIs out of the sibling repos, and record WHICH COMMIT they came from.
#
# The recording half is the point. Artifacts are gitignored build output in both contract repos, so
# there is no way to fetch a canonical ABI without compiling — which means a consumer cannot tell a
# current ABI from a stale one by looking at it. AbleToken and EVMAIAgentEscrow sat 12 days behind
# able-contracts#24 and tokenized-ai-agent#86 with a green suite the whole time, because nothing
# recorded where they came from.
#
# SOURCE.json is that record: the same pin-the-upstream-commit pattern this org already uses for the
# Brain (EXPECTED_BRAIN_SHA). It does not prevent drift; it makes drift answerable in one look.
set -eu

# Anchor to the repo root before resolving anything. Every path below is relative — the sibling
# repos via `..`, the destination via `./src` — so invoking this as `sh scripts/sync-contracts.sh`
# from anywhere but the root would look for the siblings in the wrong place and copy to the wrong
# place. `bun run sync-contracts` happens to set the CWD for us; nothing else does.
cd "$(dirname "$0")/.." || exit 1

R="${REPOS_ROOT:-..}"
ABI_DIR="./src/lib/abi"

for pair in \
  "$R/tokenized-ai-agent/artifacts/contracts/EVMAIAgent.sol/EVMAIAgent.json" \
  "$R/tokenized-ai-agent/artifacts/contracts/EVMAIAgentEscrow.sol/EVMAIAgentEscrow.json" \
  "$R/able-contracts/artifacts/contracts/AbleToken.sol/AbleToken.json"
do
  if [ ! -f "$pair" ]; then
    echo "error: canonical artifact missing: $pair" >&2
    echo "       compile the sibling repo first (its artifacts/ is gitignored build output)." >&2
    exit 1
  fi
  cp "$pair" "$ABI_DIR/"
done

ABLE_SHA=$(git -C "$R/able-contracts" rev-parse HEAD)
TA_SHA=$(git -C "$R/tokenized-ai-agent" rev-parse HEAD)

# Warn rather than fail on a dirty source tree: the ABI is still whatever was compiled, but the
# recorded SHA would not fully describe it.
for repo in able-contracts tokenized-ai-agent; do
  if [ -n "$(git -C "$R/$repo" status --porcelain)" ]; then
    echo "warning: $repo has uncommitted changes — the recorded commit may not describe these ABIs." >&2
  fi
done

# Fingerprint the INTERFACE each ABI exposes, so the manifest attests the files it names rather
# than merely sitting beside them. Without it, `cp`ing a freshly-compiled ABI into place and
# committing leaves the recorded commit describing something else entirely, with a green suite.
# Hashing the parsed `abi` rather than the bytes keeps `prettier --write` from reddening the test
# over whitespace nobody depends on.
fingerprint() {
  # ESM imports, not require(): package.json declares "type": "module". Bun happens to expose a
  # CJS shim in `bun -e` regardless, but relying on that would make this the one place in the
  # repo written against an undocumented escape hatch. Matches how abi-sync.test.ts imports the
  # same two modules. `bun -e <code> <arg>` puts the argument at process.argv[1].
  bun -e 'import { readFileSync } from "fs";
          import { createHash } from "crypto";
          process.stdout.write(createHash("sha256")
            .update(JSON.stringify(JSON.parse(readFileSync(process.argv[1], "utf8")).abi))
            .digest("hex"))' "$1"
}

ABLE_FP=$(fingerprint "$ABI_DIR/AbleToken.json")
AGENT_FP=$(fingerprint "$ABI_DIR/EVMAIAgent.json")
ESCROW_FP=$(fingerprint "$ABI_DIR/EVMAIAgentEscrow.json")

cat > "$ABI_DIR/SOURCE.json" <<JSON
{
  "_comment": [
    "Which upstream commit each committed ABI was generated from. Regenerated by \`bun run sync-contracts\`.",
    "This is the EXPECTED_BRAIN_SHA pattern applied to ABIs: the pin makes staleness INSPECTABLE.",
    "Before this file existed, the only way to notice drift was to diff against a local build —",
    "which is why AbleToken and EVMAIAgentEscrow sat 12 days stale behind able-contracts#24 and",
    "tokenized-ai-agent#86 with a green suite the whole time.",
    "To check for drift: compare these SHAs against the default branch of each repo.",
    "abiSha256 is sha256 of JSON.stringify(artifact.abi) — the interface, not the file, so",
    "reformatting does not break it. abi-sync.test.ts recomputes and compares it, which is what",
    "stops an ABI arriving by any route other than this script."
  ],
  "sources": {
    "AbleToken.json":        { "repo": "TradableApp/able-contracts",     "commit": "$ABLE_SHA", "abiSha256": "$ABLE_FP" },
    "EVMAIAgent.json":       { "repo": "TradableApp/tokenized-ai-agent", "commit": "$TA_SHA", "abiSha256": "$AGENT_FP" },
    "EVMAIAgentEscrow.json": { "repo": "TradableApp/tokenized-ai-agent", "commit": "$TA_SHA", "abiSha256": "$ESCROW_FP" }
  }
}
JSON

printf 'ABIs synced. able-contracts=%.7s tokenized-ai-agent=%.7s\n' "$ABLE_SHA" "$TA_SHA"
